local t = {}

function load_job(sj, gname, type, squad, groups)

--' created by Mora

--'--------------------------------------------------------------------------
--' ATP_FOR_TEST22
--'--------------------------------------------------------------------------

   	if type == "atp_baza" then
		-- у костра
		t = { section = "logic@atp_baza_kamp1",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_kamp2",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		-- часовые и патрулирующие
		t = { section = "logic@atp_baza_walker1",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker2",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker3",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker4",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker5",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker6",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker7",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker8",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker9",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker10",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@atp_baza_walker11",
         		idle = 0,
        		prior = 6, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
end

function load_states(gname, type)

	if type == "atp_baza" then
		return function(gulag)
			if db.actor ~= nil then
					return 0  -- день
			else
				return gulag.state
			end
		end
	end
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)

	if gulag_type == "atp_baza" then
		return npc_community == "monolits"
	end

	return false
end

function checkMonster(npc_community, gulag_type)

	return false
end